
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdroqinkssmfetjdaoqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impkcm9xaW5rc3NtZmV0amRhb3FwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2OTM2ODgsImV4cCI6MjA2MDI2OTY4OH0.EOdvRM0sg4LnL6y1GEhBivcDXP52UAGvaV5tGOJ9lQU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});
