# Generated by Django 5.0.14 on 2025-04-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('sensor_id', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('co2', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='sensorreading',
            constraint=models.UniqueConstraint(fields=('time', 'sensor_id'), name='unique_sensor_reading'),
        ),
    ]
